### ISSUE TITLE
Doofania playthrough bug

### ISSUE THREAD

**Issue by Fredson04** [ZerdNerd/crossoverworldmod#3]
**Describe the bug**
Around 1937 I got an event by the tiger clan for a treaty, however I did not have the option to refuse

**In-game details (if bug/error appears when playing the game)**
1) Doofania
2) 1937
3) No crash, this is just a missing event option
4) 

**Additional info**
Cant say much more about this. Btw there is a spelling mistake at the focus 'Preapare the fleet' from doofania, and there are no advisors (idk if this is intended)

**Comment by ZerdNerd** [comment]
So this is _intended_ as Tiger Clan needs someone for tech advancement. No refusal option exists simply because Tiger player won't have any problems this way (and the country that receives the proposal gets some benefits anyway).

No advisors is WIA as TSA rework is planned for 0.4. Typo acknowledged.
